package com.tvpy.app;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Contiene la lista de nombres de los canales recomendados que
 * se muestran en la página de inicio de la versión web de la app.
 */
public class RecommendedChannels {
    public static final Set<String> NAMES = new HashSet<>(Arrays.asList(
        "A24 Argentina",
        "ABC-TV Paraguay",
        "América TV Argentina",
        "Andalucía Cocina (1080p)",
        "Antena Uno RadioVideo (360p)",
        "Azteca Internacional (México)",
        "Bruno Masi TV",
        "C9N",
        "CBN Español (1080p)",
        "Canal 5 (Televisa) (México)",
        "Canal Pro",
        "Caracol TV (Colombia)",
        "Claro Sports",
        "Crimen & Historia (Español)",
        "DW en Español",
        "Dance FM (720p)",
        "Deportes TVC (1080p)",
        "E40",
        "ESPN Deportes",
        "Euronews en Español",
        "EWTN Spain & Latin America (720p)",
        "Enlace (720p)",
        "FIFA+ Spain (720p)",
        "FOX (Estados Unidos)",
        "FS1 (Estados Unidos)",
        "Farra Play (720p) [Not 24/7]",
        "France 24 Español",
        "Gen",
        "Golazo Network",
        "GolTV Latinoamérica",
        "HEi Now",
        "ITV Deportes (720p)",
        "Las Estrellas (México) [Geo-blocked]",
        "Latele",
        "MiTV",
        "Monumental TV",
        "NOW 70s (720p)",
        "NOW 80s (1080p)",
        "NOW 90s00s (1080p)",
        "NOW Rock (1080p)",
        "NPY",
        "NatureTime (Español)",
        "Next HD",
        "Noticias Telemundo",
        "Paraguay TV",
        "Paravisión",
        "Pluto TV Animales (Español)",
        "Pluto TV Historia (Español)",
        "Pluto TV Naturaleza (Español)",
        "Popu TV",
        "Productiva TV",
        "RDN (1080p) [Not 24/7]",
        "RT en Español",
        "RTVE Canal 24 Horas",
        "RTVE La 1",
        "Rally TV (Internacional)",
        "Real Madrid TV",
        "Red Bull TV (Español)",
        "Red Digital",
        "Runtime Cine y Series",
        "SNT",
        "Sky News (Inglés)",
        "Smithsonian Channel (Español)",
        "Stingray Classica (1080p)",
        "Stingray Greatest Holiday Hits",
        "Stingray Karaoke (1080p)",
        "Stingray Naturescape (1080p)",
        "Stingray Romance Latino (1080p)",
        "Stingray Today's Latin Pop (1080p)",
        "Stingray Urban Beat (1080p)",
        "SuperTennis (Italia)",
        "Supermúsica TV (720p)",
        "TV Globo Bahia (Brasil)",
        "TV Pública (Argentina)",
        "Terra Mater WILD (Inglés)",
        "Teledeporte (1080p)",
        "Telefe Internacional (Argentina)",
        "Telefuturo",
        "Telemundo (Estados Unidos)",
        "Tennis Channel (Internacional)",
        "Tigo Sports",
        "Tigo Sports (1080p)",
        "Tigo Sports+",
        "Totalmusic (1080p)",
        "Totalmusic 2000s (720p)",
        "Totalmusic 80s (720p)",
        "Totalmusic Concerts (720p)",
        "Totalmusic Dance (720p)",
        "Trece",
        "Tropicalia 93.9 FM",
        "TyC Sports (1080p)",
        "TyC Sports USA",
        "Unicanal",
        "Universo (Estados Unidos)",
        "Venus Media",
        "Vevo Latino (1080p)",
        "Vevo Pop (1080p)",
        "WildEarth (Inglés - Safaris en vivo)",
        "beIN Sports XTRA en Español (1080p)",
        "Ñandutí"
    ));
}
