package com.tvpy.app;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Contiene la lista de nombres de los canales recomendados que
 * se muestran en la página de inicio de la versión web de la app.
 */
public class RecommendedChannels {
    public static final Set<String> NAMES = new HashSet<>(Arrays.asList(
        "A24 Argentina",
        "ABC-TV Paraguay",
        "América TV Argentina",
        "Andalucía Cocina (1080p)",
        "Azteca Deportes Network",
        "Azteca Internacional (México)",
        "Best of Dance TV (1080p)",
        "C9N",
        "CBN Español (1080p)",
        "Canal Pro",
        "Caracol TV (Colombia)",
        "Chilevisión (Chile)",
        "Claro Sports",
        "Clubbing TV (720p)",
        "DW en Español",
        "DanceTV Deep House (1080p)",
        "DanceTV Techno Warehouse (720p)",
        "Deportes TVC (1080p)",
        "Discovery Channel (Español)",
        "Discovery Home & Health (Español)",
        "Discovery Kids (Español)",
        "Discovery Turbo (Estados Unidos)",
        "Discovery World (Español)",
        "El Garage TV (Argentina)",
        "E40",
        "ESPN (Brasil)",
        "ESPN (Señal Principal)",
        "ESPN 2",
        "ESPN 2 (Brasil)",
        "ESPN 3",
        "ESPN 3 (Brasil)",
        "ESPN 4",
        "ESPN 4 (Brasil)",
        "ESPN 5",
        "ESPN 6",
        "ESPN 7",
        "ESPN Extra (Brasil)",
        "ESPN Premium",
        "ESPN8: The Ocho",
        "Euronews en Español",
        "EWTN Spain & Latin America (720p)",
        "Enlace (720p)",
        "FIFA+ Spain (720p)",
        "FOX (Estados Unidos)",
        "Fox Deportes",
        "Fox Sports 1",
        "Fox Sports 2",
        "Fox Sports 3",
        "FS1 (Estados Unidos)",
        "Farra Play (720p) [Not 24/7]",
        "France 24 Español",
        "Gen",
        "Golazo Network",
        "GolTV Latinoamérica",
        "HEi Now",
        "Historia (España)",
        "Historia y Vida",
        "History 2 (Latinoamérica)",
        "History Channel (Latinoamérica)",
        "Investigation Discovery (ID) (Español)",
        "ITV Deportes (720p)",
        "Las Estrellas (México) [Geo-blocked]",
        "Latele",
        "Monumental TV",
        "Motorvision TV (Español)",
        "NOW 70s (720p)",
        "NOW 80s (1080p)",
        "NOW 90s00s (1080p)",
        "NOW Rock (1080p)",
        "NPY",
        "Nat Geo Wild (Español)",
        "National Geographic (Español)",
        "NatureTime (Español)",
        "Next HD",
        "Paraguay TV",
        "Paravisión",
        "Pluto TV Animales (Español)",
        "Pluto TV Documentales (Español)",
        "Pluto TV Historia (Español)",
        "Pluto TV Naturaleza (Español)",
        "Popu TV",
        "Productiva TV",
        "Radio Ibiza TV (720p)",
        "RDN (1080p) [Not 24/7]",
        "RT Documentary (Internacional)",
        "RT en Español",
        "RTVE La 1",
        "Rally TV (Internacional)",
        "Real Madrid TV",
        "Red Bull TV (Español)",
        "Red Digital",
        "Runtime Cine y Series",
        "SNT",
        "Sky News (Inglés)",
        "Smithsonian Channel (Español)",
        "Stingray Classica (1080p)",
        "Stingray Greatest Holiday Hits",
        "Stingray Karaoke (1080p)",
        "Stingray Naturescape (1080p)",
        "Stingray Romance Latino (1080p)",
        "Stingray Today's Latin Pop (1080p)",
        "Stingray Urban Beat (1080p)",
        "SuperTennis (Italia)",
        "Supermúsica TV (720p)",
        "TV Globo Bahia (Brasil)",
        "TV Pública (Argentina)",
        "Teledeporte (1080p)",
        "Telefe Internacional (Argentina)",
        "Telefuturo",
        "Telemundo (Estados Unidos)",
        "Tennis Channel (Internacional)",
        "Terra Mater WILD (Inglés)",
        "The Fishing & Hunting Channel",
        "Tigo Sports (Paraguay)",
        "Top Gear (24/7)",
        "Totalmusic (1080p)",
        "Totalmusic 2000s (720p)",
        "Totalmusic 80s (720p)",
        "Totalmusic Concerts (720p)",
        "Totalmusic Dance (720p)",
        "Trece",
        "TyC Sports (1080p)",
        "TyC Sports USA",
        "Unicanal",
        "Universo (Estados Unidos)",
        "Venus Media",
        "Vevo Latino (1080p)",
        "Vevo Pop (1080p)",
        "Waypoint TV (Estados Unidos)",
        "WildEarth (Inglés - Safaris en vivo)",
        "beIN Sports XTRA en Español (1080p)",
        "Ñandutí"
    ));
}
